# Generated by Django 5.1.7 on 2025-03-14 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('text_content', models.TextField()),
                ('file_path', models.CharField(blank=True, max_length=512, null=True)),
                ('gutenberg_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('centrality_score', models.FloatField(default=0.0)),
                ('total_clicks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BookClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchengine.book')),
            ],
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=255)),
                ('is_regex', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('clicked_books', models.ManyToManyField(through='searchengine.BookClick', to='searchengine.book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bookclick',
            name='search_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchengine.searchlog'),
        ),
        migrations.CreateModel(
            name='BookIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=100)),
                ('occurrences', models.IntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indices', to='searchengine.book')),
            ],
            options={
                'indexes': [models.Index(fields=['word'], name='searchengin_word_8d7eba_idx')],
                'unique_together': {('book', 'word')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='bookclick',
            unique_together={('search_log', 'book')},
        ),
    ]
