# Generated by Django 5.1.7 on 2025-03-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='text_content',
        ),
        migrations.AlterField(
            model_name='book',
            name='file_path',
            field=models.CharField(blank=True, default='books_data/unknown.txt', max_length=512),
        ),
    ]
