# Generated by Django 5.1.7 on 2025-03-25 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0002_remove_book_text_content_alter_book_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(default=0.0)),
                ('from_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_similarities', to='searchengine.book')),
                ('to_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_similarities', to='searchengine.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='similar_books',
            field=models.ManyToManyField(related_name='related_books', through='searchengine.BookSimilarity', to='searchengine.book'),
        ),
        migrations.AddIndex(
            model_name='booksimilarity',
            index=models.Index(fields=['from_book'], name='searchengin_from_bo_d0aa9f_idx'),
        ),
        migrations.AddIndex(
            model_name='booksimilarity',
            index=models.Index(fields=['to_book'], name='searchengin_to_book_63ca2d_idx'),
        ),
        migrations.AddIndex(
            model_name='booksimilarity',
            index=models.Index(fields=['similarity_score'], name='searchengin_similar_63cdd6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='booksimilarity',
            unique_together={('from_book', 'to_book')},
        ),
    ]
