# Generated by Django 5.1.7 on 2025-04-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0004_word_wordoccurrence'),
    ]

    operations = [
        # Skip creating OptimalIndex model since the optimal_index table already exists
        # migrations.CreateModel(
        #     name='OptimalIndex',
        #     fields=[
        #         ('word', models.CharField(max_length=100, primary_key=True, serialize=False)),
        #         ('book_ids', models.TextField()),
        #         ('book_counts', models.TextField()),
        #         ('total_occurrences', models.IntegerField(default=0)),
        #     ],
        #     options={
        #         'db_table': 'optimal_index',
        #     },
        # ),
        migrations.RemoveField(
            model_name='wordoccurrence',
            name='word',
        ),
        migrations.AlterUniqueTogether(
            name='wordoccurrence',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wordoccurrence',
            name='book',
        ),
        migrations.DeleteModel(
            name='BookIndex',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
        migrations.DeleteModel(
            name='WordOccurrence',
        ),
    ]
