# Generated by Django 5.1.7 on 2025-04-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0005_remove_bookindex'),
    ]

    operations = [
        # Skip creating OptimalIndex model since the optimal_index table already exists
        # We need to keep the model in Django's ORM though, so we'll use a RunPython operation
        # that does nothing but allows the migration to be applied
        migrations.RunPython(
            code=lambda apps, schema_editor: None,
            reverse_code=lambda apps, schema_editor: None,
        )
    ]
