# Generated by Django 5.1.7 on 2025-04-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0007_remove_bookindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimalIndex',
            fields=[
                ('word', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('book_ids', models.TextField()),
                ('book_counts', models.TextField()),
                ('total_occurrences', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'optimal_index',
            },
        ),
    ]
